# Generated by Django 2.2.2 on 2019-07-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190709_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_description',
            field=models.TextField(blank=True, default='Here is a nice description that someone did not have time to type up'),
        ),
    ]
